# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_panel_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import uic
from PyQt5.QtWidgets import *

#pyQT5 ui 파일 로드
ui_form = uic.loadUiType("main_panel_v1.ui")[0]

class MainWindow(QMainWindow, ui_form):
	def __init__(self):
		super().__init__()
		self.setupUi(self)
		
		self.i = 1;
		
		#현재 시간 디스플레이
		self.currentDateTime = QDateTime.currentDateTime() # 시간 받아옴
		#self.dateTimeEdit.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		#self.dateTimeEdit2.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		
		#시간 표시하기 위한 Timer
		self.timer = QTimer(self)
		self.timer.start(1000)
		self.timer.timeout.connect(self.cb_timeout) #1초마다 timeout 이벤트가 발생하며, timeout 함수를 호출함
		
	def cb_timeout(self):
		self.currentDateTime = QDateTime.currentDateTime() # 시간 받아옴
		self.dateTimeEdit.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		self.dateTimeEdit2.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		self.card1_textbox.setText(str(self.i))
		self.i += 1
		

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    h_window = MainWindow()
    h_window.show()
    sys.exit(app.exec_())
