# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_panel_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import uic
from PyQt5.QtWidgets import *

import serial
import threading
#import timeout
import config
#import Message

#pyQT5 ui 파일 로드
ui_form = uic.loadUiType("main_panel.ui")[0]
timer = QTimer()

class MainWindow(QMainWindow, ui_form):
	def __init__(self):
		super().__init__()
		self.setupUi(self)
		self.setFixedSize(800, 480)
		
		#현재 시간 디스플레이
		self.currentDateTime = QDateTime.currentDateTime() # 시간 받아옴
		self.dateTimeEdit.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		self.dateTimeEdit2.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		
		#시간 표시하기 위한 Timer
		timer.start(1000)
		timer.timeout.connect(self.cb_timeout) #1초마다 timeout 이벤트가 발생하며, timeout 함수를 호출함
		
		#종료 버튼 활성화
		self.pushButton_exit1.clicked.connect(QCoreApplication.instance().quit)
		self.pushButton_exit2.clicked.connect(QCoreApplication.instance().quit)
		
		#serial 통신 연결을 위한 config 파일 load
		cfg = config.Env_Config()
		
		#serial 통신 연결 시도
		try:
			card1_ser = serial.Serial(cfg.CARD1, 115200, timeout=0.2)
		except (OSError, serial.SerialException):
			print('CARD1 통신 포트 연결 실패!! ')
			
		try:
			card2_ser = serial.Serial(cfg.CARD2, 115200, timeout=0.2)
		except (OSError, serial.SerialException):
			print('CARD2 통신 포트 연결 실패!! ')
			
		try:
			qr1_ser = serial.Serial(cfg.QR1, 115200, timeout=0.2)
		except (OSError, serial.SerialException):
			print('QR1 통신 포트 연결 실패!! ')
			
		try:
			qr2_ser = serial.Serial(cfg.QR2, 115200, timeout=0.2)
		except (OSError, serial.SerialException):
			print('QR2 통신 포트 연결 실패!! ')
		
		#통신 연결 시도 끝
		

	def cb_timeout(self):
		self.currentDateTime = QDateTime.currentDateTime() # 시간 받아옴
		self.dateTimeEdit.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		self.dateTimeEdit2.setDateTime(self.currentDateTime) # 받아온 시간을 GUI 에 표시
		
		#self.card1_textbox.setText(str(self.i))
		

if __name__ == "__main__":
	import sys
	app = QApplication(sys.argv)
	h_window = MainWindow()
	h_window.show()
	ret = app.exec_()
	timer.stop()
	sys.exit(ret)

